### ISSUE TITLE
Metric name template

### ISSUE THREAD

**Issue by adrienbrault** [liuggio/StatsDClientBundle#32]
I would like to be able to have the route name, or some default in all or some of the metric name.

```
collectors:
    liuggio_stats_d_client.collector.dbal: 'my-app.{route}.query'
    liuggio_stats_d_client.collector.visitor: 'my-app.{route}.visitor'
    liuggio_stats_d_client.collector.memory: 'my-app.{route}.memory'
    liuggio_stats_d_client.collector.user: 'my-app.{route}.user'
    liuggio_stats_d_client.collector.exception: 'my-app.{route}.exception'
    liuggio_stats_d_client.collector.time: 'my-app.{route}.time'
```
