### ISSUE TITLE
DBAL collector config

### ISSUE THREAD

**Issue by eMerzh** [liuggio/StatsDClientBundle#56]
The config suggested in the doc does not work, wich lead to a non working collector

```yml
# Doctrine Configuration
doctrine:
    dbal:
        profiling: true
```
```
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized option "profiling" under "doctrine.dbal"
```

**Comment by eMerzh** [comment]
it seems that it should the correct configuration is 
under the db configuration
```yml
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
                profiling: true
                logging: true
```
(profiling AND logging seems important here)

it might be a good idea to update the doc
